name: Random test
on:
 push:
  branches: 
    - master

jobs: 
 Cypress-Test:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v2
   - name: Run Cypress
     uses: cypress-io/github-action@v6
