name: Random test
on:
 push:
  branches: 
    - master

jobs: 
 Cypress-Test:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v2
   - name: Setup
     uses: actions/setup-node@v3
   - name: Run Cypress
     uses: cypress-io/github-action@v2
     
     with:
      command: npm run scripts
